// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcceptTransfer(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function AddFriend(arg1:string):Promise<void>;

export function AutoCreateProfile(arg1:string):Promise<void>;

export function AutoLoadProfile():Promise<void>;

export function CheckProfileExists():Promise<boolean>;

export function ClearStartupFilePath():Promise<void>;

export function ClearTransferHistory():Promise<void>;

export function EmitCombinedPeers():Promise<void>;

export function GetActivePeers():Promise<Array<main.Peer>>;

export function GetDownloadsFolder():Promise<string>;

export function GetPeerID():Promise<string>;

export function GetProfileColor():Promise<string>;

export function GetProfileStatus():Promise<string>;

export function GetPublicKeyHex():Promise<string>;

export function GetServerAddress():Promise<string>;

export function GetStartupFilePath():Promise<string>;

export function GetTransfers():Promise<Array<main.TransferState>>;

export function GetUsername():Promise<string>;

export function LoginProfile(arg1:string):Promise<void>;

export function Logout():Promise<void>;

export function OpenFolderAndSelect(arg1:string):Promise<void>;

export function OpenReceivedFile(arg1:string):Promise<void>;

export function PauseTransfer(arg1:string):Promise<void>;

export function RegisterProfile(arg1:string,arg2:string):Promise<void>;

export function RemoveFriend(arg1:string):Promise<void>;

export function ResumeTransfer(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectFolderToSend():Promise<string>;

export function SelectMultipleFiles():Promise<Array<string>>;

export function SendFileToPeer(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function SendFolderToPeer(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function SendPathToPeer(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function SendTextMessage(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string>;

export function UpdateProfile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateServerAddress(arg1:string):Promise<void>;
