// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptTransfer(arg1, arg2, arg3) {
  return window['go']['main']['App']['AcceptTransfer'](arg1, arg2, arg3);
}

export function AddFriend(arg1) {
  return window['go']['main']['App']['AddFriend'](arg1);
}

export function AutoCreateProfile(arg1) {
  return window['go']['main']['App']['AutoCreateProfile'](arg1);
}

export function AutoLoadProfile() {
  return window['go']['main']['App']['AutoLoadProfile']();
}

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function CheckProfileExists() {
  return window['go']['main']['App']['CheckProfileExists']();
}

export function ClearStartupFilePath() {
  return window['go']['main']['App']['ClearStartupFilePath']();
}

export function ClearTransferHistory() {
  return window['go']['main']['App']['ClearTransferHistory']();
}

export function EmitCombinedPeers() {
  return window['go']['main']['App']['EmitCombinedPeers']();
}

export function GetActivePeers() {
  return window['go']['main']['App']['GetActivePeers']();
}

export function GetDownloadsFolder() {
  return window['go']['main']['App']['GetDownloadsFolder']();
}

export function GetFilePreview(arg1) {
  return window['go']['main']['App']['GetFilePreview'](arg1);
}

export function GetPeerID() {
  return window['go']['main']['App']['GetPeerID']();
}

export function GetProfileColor() {
  return window['go']['main']['App']['GetProfileColor']();
}

export function GetProfileStatus() {
  return window['go']['main']['App']['GetProfileStatus']();
}

export function GetPublicKeyHex() {
  return window['go']['main']['App']['GetPublicKeyHex']();
}

export function GetServerAddress() {
  return window['go']['main']['App']['GetServerAddress']();
}

export function GetStartupFilePath() {
  return window['go']['main']['App']['GetStartupFilePath']();
}

export function GetTransfers() {
  return window['go']['main']['App']['GetTransfers']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function HandleStartupFilePath(arg1) {
  return window['go']['main']['App']['HandleStartupFilePath'](arg1);
}

export function LoginProfile(arg1) {
  return window['go']['main']['App']['LoginProfile'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenFolderAndSelect(arg1) {
  return window['go']['main']['App']['OpenFolderAndSelect'](arg1);
}

export function OpenReceivedFile(arg1) {
  return window['go']['main']['App']['OpenReceivedFile'](arg1);
}

export function PauseTransfer(arg1) {
  return window['go']['main']['App']['PauseTransfer'](arg1);
}

export function RegisterProfile(arg1, arg2) {
  return window['go']['main']['App']['RegisterProfile'](arg1, arg2);
}

export function RemoveFriend(arg1) {
  return window['go']['main']['App']['RemoveFriend'](arg1);
}

export function ResolvePeerName(arg1, arg2) {
  return window['go']['main']['App']['ResolvePeerName'](arg1, arg2);
}

export function ResumeTransfer(arg1) {
  return window['go']['main']['App']['ResumeTransfer'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolderToSend() {
  return window['go']['main']['App']['SelectFolderToSend']();
}

export function SelectMultipleFiles() {
  return window['go']['main']['App']['SelectMultipleFiles']();
}

export function SendFileToPeer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendFileToPeer'](arg1, arg2, arg3, arg4);
}

export function SendFolderToPeer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendFolderToPeer'](arg1, arg2, arg3, arg4);
}

export function SendFriendRequest(arg1) {
  return window['go']['main']['App']['SendFriendRequest'](arg1);
}

export function SendPathToPeer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendPathToPeer'](arg1, arg2, arg3, arg4);
}

export function SendTextMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendTextMessage'](arg1, arg2, arg3, arg4);
}

export function UpdateProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3);
}

export function UpdateServerAddress(arg1) {
  return window['go']['main']['App']['UpdateServerAddress'](arg1);
}
